- spyder_kernels/site/sitecustomize.py
Kernel was stuck when started from Spyder before these changes,
> PR: Fix some errors in sitecustomize

- spyder_kernels/__init__.py
This is needed to do some validations in Spyder.
> PR: Add __version__ to package's init

- spyder_kernels/utils/nsview.py
Needed to fix Spyder [#7312](https://github.com/spyder-ide/spyder/issues/7312)
> PR: Handle deprecated 'summary' method for Pandas

- setup.py
- spyder_kernels/customize/spydercustomize.py
This avoids several errors with Tornado `>=5.0`.
> PR: Demand specific dependency versions needed by Spyder

- .circleci/config.yml
- .circleci/install.sh
- .circleci/run_tests.sh
- spyder_kernels/utils/tests/test_dochelpers.py
This uses the new Circle 2.0 configuration.
> PR: Start testing with CircleCI

- spyder_kernels/console/start.py
Fixes #14 
needs a PR for Spyder config as well
> PR: Separate startup run_lines with semicolon instead of comma

- MANIFEST.in
Counterpart to #20 ; forgot to do this when I added it in #18 . Sorry!
> PR: Add AUTHORS.txt in MANIFEST.in to include in package

- spyder_kernels/ipdb/kernel.py
- spyder_kernels/ipdb/tests/test_ipdb_kernel.py
> PR: Remove unnecessary magics from IPdb kernel

- spyder_kernels/ipdb/kernel.py
- spyder_kernels/ipdb/tests/test_ipdb_kernel.py
- spyder_kernels/utils/module_completion.py
- spyder_kernels/utils/tests/test_modulecompletion.py
Completions were not as good as in a regular IPython session. Now they should be pretty close.
> PR: Improve completions for the IPdb kernel

- spyder_kernels/ipdb/kernel.py
- spyder_kernels/ipdb/spyderpdb.py
- spyder_kernels/ipdb/tests/test_ipdb_kernel.py
> PR: Make do_inspect and help work as in IPython

- spyder_kernels/ipdb/kernel.py
- spyder_kernels/ipdb/tests/test_ipdb_kernel.py
> PR: Override 'do_complete' method to prevent duplicated path matches

- .circleci/install.sh
- setup.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
> PR: Add the Wurlitzer package to capture stdout/stderr from C libraries

- spyder_kernels/customize/spydercustomize.py
> PR: Filter deprecation warnings in ipykernel

- .circleci/run_tests.sh
- README.md
- appveyor.yml
- spyder_kernels/console/tests/test_console_kernel.py
> PR: Test on Windows with Appveyor

- setup.py
- spyder_kernels/console/kernel.py
> PR: Don't load Wurlitzer extension on Windows because it has no effect there

- .circleci/install.sh
- .circleci/run_tests.sh
- appveyor.yml
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
Fixes spyder-ide/spyder#8128
TODO:
> PR: Patch multiprocessing to make it work when all variables are removed

- spyder_kernels/console/tests/test_console_kernel.py
> PR: Add a test for the runcell command

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/nsview.py
> PR: Fix numpy printoptions format

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
> PR: Have runcell set __file__ to the path of the file containing the cell 

- spyder_kernels/customize/spydercustomize.py
> PR: Remove user module reloader from runcell

- spyder_kernels/customize/spydercustomize.py
> PR: Blacklist tensorflow from the UMR

- .coveragerc
- .gitignore
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/tests/__init__.py
- spyder_kernels/customize/tests/test_spydercustomize.py
The criteria that Pierre set for this many years ago was not working as expected these days.
> PR: Better way to skip standard library and site-packages modules from UMR

- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/tests/test_spydercustomize.py
Fixes #85.
This also adds some more tests to avoid things like #85 in the future.
> PR: Fix problems with UMR's run method

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
> PR: Patch turtle.bye to make it work with multitple runnings of the same code

- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/tests/test_spydercustomize.py
> PR: Include user site-packages directory in the list of excluded paths by the UMR

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/tests/test_spydercustomize.py
> PR: Change np.nan for np.inf in test_np_threshold

- spyder_kernels/customize/spydercustomize.py
> PR:  Avoid error when trying to pop __file__ out of the current namespace

- spyder_kernels/customize/spydercustomize.py
> PR: Enclose turtle customizations in a try/except to avoid a dependency on Tk

- spyder_kernels/customize/spydercustomize.py
Part of spyder-ide/spyder#9113
> PR: Handle option to show/hide cmd windows generated by the subprocess module

- .circleci/install.sh
- appveyor.yml
- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/tests/test_iofuncs.py
> PR: Set Matplotlib backend to inline for kernels started outside Spyder

- spyder_kernels/utils/nsview.py
Part of spyder-ide/spyder#8852
> PR: Add object explorer settings to REMOTE_SETTINGS

- setup.py
> PR: Add tests requirements to setup.py

- MANIFEST.in
- setup.py
I don't know when this stopped working, but it should be fine now.
> PR: Fix not including tests in tarballs and wheels

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
This PR implements the changes needed by https://github.com/spyder-ide/spyder/pull/9014 to work. It is dependent on #111.
Fixes #97
Add a new builtin, `debugcell`, to debug a single cell
> PR: Use the comms API to improve runcell and add a new debugcell command

- setup.py
Update requirements (see https://github.com/spyder-ide/spyder/pull/10085)
> PR: Update jupyter-client minimal required version

- README.md
- setup.py
We only added it to our requirements file.
> PR: Add xarray to our test deps in setup.py

- spyder_kernels/customize/spydercustomize.py
> PR: Add current_namespace kwarg to debugfile

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
Cache the code before running the file to allow running unsaved files. Works with https://github.com/spyder-ide/spyder/pull/10115.
This PR also adds support to run IPython (`.ipy`) files in our kernel.
Fixes #139
Fixes spyder-ide/spyder#1643.
> PR: Make runfile to retrieve code from the Spyder editor and add it to linecache

- setup.py
This avoids an ugly bug on Windows.
> PR: Require more recent version of jupyter-client

- spyder_kernels/utils/nsview.py
This will give less verbose info in the Variable and Object Explorers.
> PR: Improve displayed type and value for generic objects

- spyder_kernels/comms/commbase.py
- spyder_kernels/comms/frontendcomm.py
Allow different frontends to have different pickle protocols.
> PR: Allow different frontends to have different pickle protocols

- spyder_kernels/console/kernel.py
Add methods to be able to update python path:
> PR: Add path update methods

- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
Use ipython do_complete in pub if the completion is not pdb specific for a better fit between pub and ipython completion
> PR: Use IPython completer for Pdb

- spyder_kernels/console/tests/test_console_kernel.py
> PR: Update test to work with IPython 7.10+

- spyder_kernels/console/kernel.py
Needed for spyder-ide/spyder#11357
> PR: Add method to check dependencies for special consoles

- spyder_kernels/comms/frontendcomm.py
Resend comm configuration on timeout if the configuration was not properly received.
> PR: Resend comm configuration on timeout

- spyder_kernels/comms/commbase.py
This is necessary for spyder-ide/spyder#11471
load_exception is not a special case anymore
> PR: Remove load_exception in comms

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/namespace_manager.py
Fixes https://github.com/spyder-ide/spyder/issues/1918
> PR: Remove __file__ after running script

- spyder_kernels/console/start.py
Fixes https://github.com/spyder-ide/spyder/issues/6695
> PR: Fix %varexp namespace

- spyder_kernels/customize/spydercustomize.py
Fixes https://github.com/spyder-ide/spyder/issues/2970
> PR: Patch PyQt to save created QApplication instances

- spyder_kernels/customize/spydercustomize.py
Also, only print it once to not spam users about it.
> PR: Improve message about using invalid syntax in cells and files

- spyder_kernels/console/kernel.py
- spyder_kernels/customize/namespace_manager.py
Set the running namespace correctly when sending it while debugging.
For https://github.com/spyder-ide/spyder/issues/12102
> PR: Set namespace correctly when running in new namespace

- spyder_kernels/utils/nsview.py
> PR: Avoid an error when computing the shape of Pandas objects

- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
For https://github.com/spyder-ide/spyder/issues/11986
> PR: Fix post mortem functionality

- spyder_kernels/console/start.py
Fixes https://github.com/spyder-ide/spyder/issues/12442
> PR: Check that startup file exists

- requirements/tests.txt
- setup.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
Add the multithreading patch for fixing Dask issues if working in Python 3.
Also add a regression test
Fixes https://github.com/spyder-ide/spyder/issues/12465
> PR: Make multithreading patch work for all OSes in Python 3

- spyder_kernels/customize/spydercustomize.py
Fixes https://github.com/spyder-ide/spyder/issues/12801
> PR: Fix showing full post mortem traceback

- spyder_kernels/utils/nsview.py
Part of spyder-ide/spyder#12901
> PR: Create a constant for numeric Numpy types

- spyder_kernels/customize/spydercustomize.py
Fix failing test in spyder-ide/spyder#12901
> PR: Fix post_mortem interaction

- .github/workflows/windows-tests.yml
- spyder_kernels/comms/frontendcomm.py
Send comm config any time we wait
> PR: Send comm config before any wait just to be sure

- spyder_kernels/comms/commbase.py
- spyder_kernels/comms/frontendcomm.py
Send comm config on every message
> PR: Send comm config on every message

- setup.py
> PR: Require dask[distributed] for tests

- spyder_kernels/customize/spyderpdb.py
Modify the behaviour or the `where` pdb command to go to the current place in the editor
> PR: Make do_where go to the current file

- spyder_kernels/utils/nsview.py
related to https://github.com/skjerns/spyder/tree/issue_13733
should not alter any current functionality and be backwards compatible.
> PR: Allow sorting with custom sorting key

- spyder_kernels/comms/commbase.py
- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/kernel.py
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
- spyder_kernels/py3compat.py
The way Pdb input was handled was a bit messy. This PR separates it cleanly from the rest of inputs and enables many improvments, such as running the event loop while debugging. This enables showing interactive matplotlib plots.
Required by spyder-ide/spyder#13327.
> PR: Improve Pdb input handling

- spyder_kernels/customize/spydercustomize.py
> PR: Allow leading indents in cells

- requirements/tests.txt
- setup.py
- spyder_kernels/utils/nsview.py
- spyder_kernels/utils/tests/test_nsview.py
>branching from master
>same mistake again was done
>now new pull request
Probably the worst Haiku in history. Hope I learned my lesson, this time based on 1.x 
highly related: #249
> PR: Show size of objects correctly, if they implement len()

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
Apply fix in https://github.com/python/cpython/pull/15194 to spyder-kernels
This addreses https://github.com/spyder-ide/spyder/issues/13909
> PR: Use frame locals when evaluating code in Pdb

- spyder_kernels/customize/spydercustomize.py
This is required to fix issue spyder-ide/spyder#13519 and it'll have an accompanying PR on the Spyder repo
> PR: Extend sys.path with paths that come from Spyder

- spyder_kernels/console/kernel.py
- spyder_kernels/customize/spyderpdb.py
Use '!' before Pdb commands and nothing before python code, as is the case in IPython
> PR: Use '!' for Pdb commands

- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
- spyder_kernels/utils/misc.py
* Methods for `matplolib` backend and inline backend config
* Methods to config type of completer to use and autocall
Part of spyder-ide/spyder#11357
> PR: Add methods to handle IPython console config on the fly

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
This fixes running our tests on Github acttions
> PR: Fix Github actions

- spyder_kernels/console/kernel.py
Addresses https://github.com/spyder-ide/spyder/issues/14100
> PR: Fix get_cwd permission errors

- setup.py
- spyder_kernels/customize/spydercustomize.py
This will better allows us to control the things we import from it.
Fixes #256.
> PR: Add explicit requirement on IPython

- spyder_kernels/customize/spyderpdb.py
> PR: Add space after dot in a message

- spyder_kernels/customize/utils.py
> PR: Treat 'pkgs' path as a library

- spyder_kernels/customize/spyderpdb.py
This addresses https://github.com/spyder-ide/spyder/issues/14477
> PR: Fix assignment detection in exclamation mark mode (Pdb)

- spyder_kernels/utils/nsview.py
- spyder_kernels/utils/tests/test_nsview.py
This is required to move colors for variables from here to Spyder.
> PR: Add Python types to namespace view

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- spyder_kernels/comms/frontendcomm.py
If a shutdown message is recieved on the comm channel, close comm
> PR: Close comm on shutdown

- spyder_kernels/customize/spyderpdb.py
Address https://github.com/spyder-ide/spyder/issues/15546
> PR: Pass adding breakpoint on ValueError

- setup.py
> PR: Remove pin on decorator because the Cython magic is working fine again

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/windows-tests.yml
- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/tests/test_console_kernel.py
This adds support for that version and fixes our tests.
> PR: Add support for ipykernel 6

- README.md
- spyder_kernels/console/outstream.py
- spyder_kernels/customize/spydercustomize.py
This is necessary to have better support for Rich and Colorama.
> PR: Patch os.get_terminal_size to return a terminal size

- setup.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
> PR: Fix timeit in Pdb and other namespace issues

- spyder_kernels/customize/spyderpdb.py
Fixes https://github.com/spyder-ide/spyder/issues/16780
> PR: Remove usage of f_locals.get

- spyder_kernels/utils/nsview.py
Addresses spyder-ide/spyder#16348
> PR: Add cast for shape tuple subclass instances when getting values size

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
Addresses https://github.com/spyder-ide/spyder/issues/16790
> PR: Remove locals from exec with comprehensions (debugger)

- spyder_kernels/comms/frontendcomm.py
May fix https://github.com/spyder-ide/spyder/issues/16183
> PR: Run asyncio and normal handlers

- spyder_kernels/console/shell.py
This avoids showing the following traceback, which is totally unnecessary:
> PR: Don't show traceback when exiting debugger after breakpoint call

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- CHANGELOG.md
I just noticed this after releasing 2.2.0
> PR: Fix misplaced section in changelog

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
FIxes https://github.com/spyder-ide/spyder-kernels/issues/345
> PR: Fix some namespace issues

- README.md
> PR: Update Quansight logo in Readme

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
A function definition was not correctly capturing the locals. Fixed and added a regression test.
> PR: More namespace fixes

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
See https://github.com/spyder-ide/spyder/issues/16696
> PR: Fix error when running multiprocessing code that contains classes

- .github/workflows/windows-tests.yml
- spyder_kernels/comms/frontendcomm.py
> PR: Filter another benign message coming from comm handlers

- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
Address https://github.com/spyder-ide/spyder/issues/16417 for unsaved files
> PR: Leave unsaved files in linecache

- spyder_kernels/customize/spyderpdb.py
Namespace is broken in comprehensions because the iterator variable is saved as ".0", which is not a correct identifier name
- Test in https://github.com/spyder-ide/spyder/pull/17231
- Fixes #371
> PR: Fix issues when debugging comprehensions

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/kernel.py
- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
- spyder_kernels/customize/utils.py
- spyder_kernels/py3compat.py
When entering code in ipython, if the last line is an expression, it is printed after an "Out [i]: " prompt. This PR reproduces this behaviour in the debugger.
Fixes #330
> PR: Print last line of Pdb code and some debugger fixes

- spyder_kernels/utils/nsview.py
> PR: Handle getting dasks objects size

- setup.cfg
- setup.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
This is small follow-up PR after PR #341.
> PR: Minor changes to finish the migration to Python 3

- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
Fixes https://github.com/spyder-ide/spyder-kernels/issues/394
> PR: Fix running namespace and improve eventloop integration while debugging

- spyder_kernels/customize/spyderpdb.py
#395 python2 support needs to be removed for master branch
> PR: Remove Python 2 code introduced when merging PR #395

- spyder_kernels/customize/namespace_manager.py
Avoid clearing the cached namespace in case of recursive call to runfile/debugfile. For example, calling `debugfile(...)` on a file and then at the pdb prompt running `runfile(...)` on the same file
> PR: Fix module namespace

- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
Part of https://github.com/spyder-ide/spyder/pull/14199
> PR: Notify frontend of Matplotlib backend change

- requirements/posix.txt
- requirements/windows.txt
- setup.py
> PR: Increase minimal required version of jupyter_client to 7.3.4

- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
Faster pdb by decreasing the number of comm messages
> PR: Make debugger faster by avoiding unnecessary comm messages

- spyder_kernels/console/shell.py
for https://github.com/spyder-ide/spyder/pull/19074
> PR: Add Python executable as part of kernel info

- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/customize/spyderpdb.py
5.x version of https://github.com/spyder-ide/spyder-kernels/pull/412
> PR: Flush std streams after execution

- spyder_kernels/customize/spyderpdb.py
Part of spyder-ide/spyder#17523
> PR: Fix tk eventloop handling when debugging on Windows

- requirements/posix.txt
- requirements/tests.txt
- requirements/windows.txt
- setup.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/nsview.py
- Also increase minimal version of IPykernel to 6.15.3
- Addresses spyder-ide/spyder#19516
- Addresses spyder-ide/spyder#19145
- Addresses spyder-ide/spyder#19026
> PR: Fix some errors when computing the namespace view

- spyder_kernels/utils/nsview.py
I introduced this small error when merging PR #416 to `master`
> PR: Fix error in `globalsfilter`

- spyder_kernels/customize/utils.py
Fix line number end range for Python 3.11
Fixes https://github.com/spyder-ide/spyder/issues/19862
> PR: Fix lineno range

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- requirements/posix.txt
- requirements/windows.txt
- setup.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/tests/test_dochelpers.py
- spyder_kernels/utils/tests/test_nsview.py
> PR: Update IPython requirement to support version 8

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- requirements/posix.txt
- requirements/windows.txt
- setup.py
- This avoids a bug with PyZMQ 25.
- See https://github.com/jupyter/jupyter_client/pull/914 for context.
- Addresses spyder-ide/spyder#20359
> PR: Increase minimal required Jupyter-client version to 7.4.9

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/comms/utils.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/customize/spyderpdb.py
- spyder_kernels/utils/iofuncs.py
Goes with https://github.com/spyder-ide/spyder/pull/19842
> PR: Update variable explorer from the kernel

- spyder_kernels/customize/spydercustomize.py
See commit message for details. Fixes one of the issues mentioned in #425.
> PR: Inform GUI about position of exception in post mortem debugging

- spyder_kernels/customize/spydercustomize.py
Fixes https://github.com/spyder-ide/spyder-kernels/issues/425
> PR: Fix post mortem for debugging

- setup.py
- See issue #https://github.com/spyder-ide/spyder/issues/20393 for more context.
> PR: Skip IPython versions that give buggy code completions

- requirements/posix.txt
- requirements/windows.txt
- setup.py
This is necessary for https://github.com/spyder-ide/spyder/issues/20381.
> PR: Add support for Jupyter-client 8

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- requirements/tests.txt
- setup.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/tests/test_nsview.py
Also, fix some failing tests and don't stop tests on first failure.
Fixes #454.
> PR: Remove `codecov` package and use Github action to upload coverage instead

- setup.py
This is necessary to address https://github.com/spyder-ide/spyder/issues/20871 and https://github.com/spyder-ide/spyder/issues/20816.
> PR: Skip more buggy IPython versions

- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
This is necessary to address https://github.com/spyder-ide/spyder/issues/21149
goes with https://github.com/spyder-ide/spyder/pull/21184
> Remove locals inspection

- spyder_kernels/customize/spyderpdb.py
Goes with https://github.com/spyder-ide/spyder/pull/21323
> PR: Fix index when skipping hidden frames (Debugger)

- spyder_kernels/utils/dochelpers.py
- spyder_kernels/utils/tests/test_dochelpers.py
- Addresses spyder-ide/spyder#21148.
> PR: Improve getting signatures from docstrings and catch error when trying to get the signature of some objects

- spyder_kernels/comms/commbase.py
if an error occurred while unpickling this will send it back correctly
> PR: Send back pickling error correctly

- spyder_kernels/customize/spyderpdb.py
- Addresses spyder-ide/spyder#22500.
- Supersedes #513.
> PR: Correctly process Pdb commands available in `cmdqueue`

- spyder_kernels/console/shell.py
- spyder_kernels/console/tests/test_console_kernel.py
Also, add a test to check that.
> PR: Disable magics and commands to call Python package managers

- spyder_kernels/console/kernel.py
- spyder_kernels/utils/pythonenv.py
Part of spyder-ide/spyder#23558
> PR Add pixi related utility functions and env info

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- setup.py
Also, start testing with Python 3.12.
> PR: Drop support for Python 3.8
