spyder-ide/spyder-kernels

- .circleci/config.yml
- .circleci/install.sh
- .circleci/run_tests.sh
- spyder_kernels/ipdb/backend_inline.py
- spyder_kernels/ipdb/kernel.py
- spyder_kernels/ipdb/magics/matplotlib_magic.py
- spyder_kernels/ipdb/spyderpdb.py
- spyder_kernels/ipdb/tests/test_ipdb_kernel.py
- spyder_kernels/ipdb/tests/test_matplotlib.py
Fixes #25.
TODO:
---- 
Related work:
* Override default magics in MetaKernel: Calysto/metakernel#172
* Restore Python 2 compatibility in MetaKernel: Calysto/metakernel#173
* Fix wrong handling of metadata in MetaKernel display system: Calysto/metakernel#174
> PR: Add %matplotlib magic to the IPdb kernel

- .circleci/config.yml
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
Fixes spyder-ide/spyder#8007
The cwd gets readded by IPython after the kernel starts.
> PR: Remove current working directory from sys.path before starting the console kernel

- MANIFEST.in
- setup.py
I'm doing this because this package is not easy to test locally and we don't want other projects (like Debian) to ask us how to run our test suite in their CI servers.
They'll have to trust in our CI setup.
> PR: Exclude all tests from our tarballs

- spyder_kernels/customize/spydercustomize.py
modified the ``spyder/defaults`` directory, or added new icons/assets
This PR makes a function that runs a cell instead of copying the cell contents into the current console. With this function can allow for correct traceback links when used with https://github.com/spyder-ide/spyder/pull/7310
The function reads a code section from a variable in the ipython namespace of the console. The function executes this code then deletes the variable. The function displays an error if it is run from the console. The variable could remain so the function can run the last cell, but it's not obvious that it won't reflect any subsequent changes to the cell block in the editor. The cell_mane is currently only used to show the user a simple history of what cells have been run …
> PR: Add runcell to spydercustomize

- spyder_kernels/customize/spydercustomize.py
As discussed here:
https://github.com/spyder-ide/spyder/pull/7310
This is the simple fix:
```python
ipython_shell.events.trigger('post_execute')
ipython_shell.run_cell(cell_code)
```
Pull request coming to spyder-kernels.
The new runcell command runs the pre-execution trigger 3 times (and now closes twice) before every execution, but I don't notice any performance hit.
> PR: runcell trigger post_execute before run_cell to end the run_cell pre_execute

- spyder_kernels/utils/iofuncs.py
- spyder_kernels/utils/tests/test_iofuncs.py
As a compliment to #80 on the loading namespaces side, this PR implements a number of fixes to make saving them work much more reliably and robustly, and improve the user experience when problems occur. While it is independent of any changes in Spyder, it is complimented by spyder-ide/spyder#8636 which makes the UI text less confusing should some objects fail to be serialized.
In particular, as proposed in #75 , this PR:
* Fixes error messages not being printed by handling exceptions in the ``deepcopy()`` call properly
* Calls deepcopy on each individual value rather than the whole dict/namespace, to prevent falling back to normal ``copy`` or nothing at all for everything if one object cannot be deepcopied (or serialized entirely)
* Skips serializing anything that is a Python module as …
> PR: Fix and improve saving of Spyder namespace with many types of objects

- .gitignore
Running tests sometimes(?) generate these, so `git add .` used to add them...
> Added .pickle files to .gitignore

- spyder_kernels/py3compat.py
Just a minor fix, but required for Python 3.8 support.
> PR: Fix deprecated import

- requirements/tests.txt
- spyder_kernels/utils/tests/test_nsview.py
That's because the Panel object was removed in Pandas 0.25
Fixes #132.
> PR: Replace usage of Pandas Panel for Xarray Dataset in our tests

- spyder_kernels/comms/commbase.py
- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/customize/spydercustomize.py
Give a chance to the frontend to save a file before running it.
This is the companion of spyder-ide/spyder#9966.
> PR: Ask the frontend to save files before running them

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
This is the companion of PR spyder-ide/spyder#10047.
----
Less internal levels
The file name is correct.
> PR: Improve the display of tracebacks and better handle namespace and __file__ during execution

- spyder_kernels/customize/spydercustomize.py
Set debugging state before asking for input. This avoids problems with the ipdb input being requested before the state is set.
> PR: Set debug state before asking for input

- spyder_kernels/customize/spydercustomize.py
Solve a problem where a NameError is raised while debugging.
To reproduce:
1. Start debugging a file (For example, a single print statment in a file)
2. Type `n` until debugging finishes
3. 
```python-traceback
Traceback (most recent call last):
File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 92, in trace_dispatch
return self.dispatch_return(frame, arg)
File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 151, in dispatch_return
self.user_return(frame, arg)
File "/Users/quentinpeter/pyscripts/spyder-kernels/spyder_kernels/customize/spydercustomize.py", line 480, in user_return
self._old_Pdb_user_return(frame, return_value)
File …
```
> PR: Solve error with exit command not being defined in the debugger

- spyder_kernels/console/kernel.py
Added method for setting the colors of the sympy equations depending on the background color.
Issue Spyder-ide/spyder#3798
> PR: Add a way to change foreground color of Sympy repr's

- spyder_kernels/comms/frontendcomm.py
set `comm._closed = True` to avoid closing comm after the close message.
Fixes #145.
> PR: Set closed flag before deleting comms 

- spyder_kernels/customize/spydercustomize.py
As we have a subclass of Pdb, there is no reason to do monkey-patching.
I moved all the monkey-patched methods in the subclass.
> PR: Remove Pdb Monkeypatching

- spyder_kernels/customize/spydercustomize.py
Only continue if the file has breakpoints and debugfile is being called. Otherwise post mortem debugging doesn't work.
> PR: Fix post-mortem debugging

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/py3compat.py
Adds call to the pdb autocomplete mechanism when the kernel is debugging.
This depends on my other PR because the corresponding spyder PR, https://github.com/spyder-ide/spyder/pull/9940, depends on the corresponding other PR as well.
The main reason for the dependence is that the kernel needs to be interrupted to receive the interruption request.
> PR: Add code completion to Pdb

- spyder_kernels/customize/spydercustomize.py
Reimplement Pdb.default to allow running multiline statement.
Before, pasting
```
print(0)
print(1)
```
in the debugger would give:
`*** SyntaxError: multiple statements found while compiling a single statement`
With this PR, it gives:
```
0
1
```
> PR: Allow Pdb to run multiline statments

- spyder_kernels/customize/spydercustomize.py
Now that we can debug files that don't exist locally, the calls to `os.path.isfile` must be removed.
> PR: Don't demand that a file exists in Pdb

- spyder_kernels/comms/commbase.py
- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/customize/spydercustomize.py
Calling `do_one_iteration` is not a good idea as it might process messages out of order.
Here, a new socket is created. It is a one way socket designed to skip the message queue, and runs in a thread. This means that:
- Only messages that are explicitely sent to this socket are processed out of order, instead of all messages as it is the case now.
- Any thread can make a blocking call to the frontend without needing to start an event loop.
- We can set breakpoints while executing!
> PR: Create a Comm socket

- spyder_kernels/customize/spydercustomize.py
While debugging, if the code raises a syntax error, the console becomes unusable:
```
if True:
print(0)
print(1)
```
This PR properly handles the exception
Fixes https://github.com/spyder-ide/spyder/issues/10588
> PR: Prevent pdb syntax error from blocking the console

- spyder_kernels/comms/commbase.py
- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/kernel.py
* This is to account for some calls that can pass a timeout (e.g. a get_value call from the frontend) and others that don't (which will pass by default a timeout of None).
* This also adds a timeout kwarg to `frontend_call` to have variable timeout calls from the frontend to the kernel.
> PR: Use a timeout in CommBase if a call passes one different from None

- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
`runfile` and `runcell` can be used while debugging to run code. However, the namespace is not properly set. This PR solves this problem.
> PR: Correctly set namespace while debugging

- spyder_kernels/console/kernel.py
- spyder_kernels/customize/spydercustomize.py
Add settings to trigger "pre_execute" and "post_execute" events when processing pdb code. This will for example show inline plots.
It depends on #152 as it uses the `pdb_settings` mechanism.
> PR: Add an option to execute IPython events in Pdb

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/nsview.py
This will allow us to only exclude these kind of objects by default in Spyder 4, so users can have access to the Object Explorer integrated by @dalthviz.
A PR is still missing in the Spyder side, which I'll open shortly.
> PR: Add an option to namespace view settings to exclude callables and modules

- spyder_kernels/customize/spyderpdb.py
Fix an issue where spyder is not notified on the first frame because it is None
> PR: Process first frame in Pdb

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
Fixes https://github.com/spyder-ide/spyder/issues/11023
- Allows running cell magic. E.g in python 3:
```
#%%
%%python2
print 'a'
print('b')
```
- Allows magics in .py files but raises a warning
> PR: Allow IPython magics in code again

- spyder_kernels/customize/spyderpdb.py
calling `self.curframe.f_locals` resets locals in pdb. This PR avoid that by using `self.curframe_locals` instead. (Which exists for precisely this reason)
> PR: Prevent completion from changing local objects while debugging

- spyder_kernels/console/kernel.py
Modules can fail to be imported due to a lot of issues, not just `ImportError`.
> PR: Use Exception instead of ImportError in is_special_kernel_valid

- spyder_kernels/console/__main__.py
Since that version `os.getcwd` is added by default to sys.path when using `python -m` to run a module, which is precisely what we do to start kernels in Spyder. [Here](https://docs.python.org/3/whatsnew/3.7.html#changes-in-python-behavior) is the entry about that change in the Python 3.7 release notes (it took me a couple of hours to find it).
Pinging @jitseniesen about this because (I think) we also use `python -m` in `spyder-notebook`.
TODO:
> PR: Remove the current working directory from sys.path for Python 3.7+

- spyder_kernels/customize/spydercustomize.py
This was merged incorrectly against `master` and not `1.x`.
> PR: Backport PR 225

- spyder_kernels/customize/spydercustomize.py
Add warning to avoid problems I had with https://github.com/micro-manager/pycro-manager/issues/42
Basically, if you run a script that was not saved, spyder fakes a file. As there is no `fork()` on window, `multiprocessing` can't just copy the content of the memory and has to restore the state somehow. Part of doing it is to import the main file. But if the main file doesn't exist, then that will fail.
> PR: Add warning on console if file is not saved

- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
A new method introduced in `ipykernel` **5.3.1**, added to `IPKernelApp` and called during kernel initialization prevented us to use our own debugger. Overriding it and making it pass fixed the issue. You can see PR ipython/ipykernel#490 for the details.
This PR also takes the opportunity to move several methods of `SpyderKernel` in more suitable places.
> PR: Fix a problem caused by ipykernel 5.3.1

- spyder_kernels/customize/spyderpdb.py
If an exception occur in Pdb, the frontend can find itself in an inconsistant state. This makes sure the state of the frontend is reset.
> PR: Set debug state correctly on exception

- spyder_kernels/console/kernel.py
While debugging, the `%timeit` magic doesn't set the local scope correctly. Together with https://github.com/ipython/ipython/pull/12437, this PR solves this problem by correctly setting the locals while debugging.
> PR: Set get_local_scope correctly while debugging

- spyder_kernels/customize/spydercustomize.py
sets "Original wdir" before running a file
Fixes spyder-ide/spyder#13632
> PR: Set multiprocessing ORIGINAL_DIR at startup

- spyder_kernels/customize/spydercustomize.py
Use the new feature introduced in https://github.com/ipython/ipython/pull/12359 to hide spyder internals
> PR: Hide runcell and runfile frames using a new IPython feature

- spyder_kernels/utils/nsview.py
This address https://github.com/spyder-ide/spyder/issues/13891 and spyder-ide/spyder#13892
having __len__ doesn't mean len will return without errors
> PR: Catch errors when trying to get the len of an object

- spyder_kernels/customize/spyderpdb.py
The warning was being printed when not using pdb commands
> PR: Fix warning for '!' Pdb option

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- spyder_kernels/utils/misc.py
This is necessary to not report that a module is installed when it can imported but only its `__pycache__` directory is present (due to an incorrect uninstallation).
> PR: Add extra validation to is_module_installed

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/kernel.py
Close the comms thread to avoid hanging while quitting. To reproduce:
`python -m spyder-kernels.console`
Connect to the console, send `quit()`
See that the console doesn't quit
> PR: Avoid infinite hang when quitting external kernels

- spyder_kernels/customize/spyderpdb.py
If a user want to quit the debugging, he might write quit or exit. Avoid that doing that closes the kernel instead.
> PR: Add exception for quit and exit in SpyderPdb

- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
Addresses https://github.com/spyder-ide/spyder/issues/14472
> PR: Fix recursive debugger

- spyder_kernels/console/tests/test_console_kernel.py
This addresses the "easy" part of #274 by testing for the ability to run turtle explicitly (in case tkinter is installed but the test is running in a non-graphical context).
> PR: Better test for non-interactive context

- spyder_kernels/comms/frontendcomm.py
Addresses https://github.com/spyder-ide/spyder/issues/14551
```
In [1]: class A():
...:     @property
...:     def shape(self):
...:         print((1234, 1))
...:         return 1234, 1
In [2]: a = A()
Output from spyder call 'get_namespace_view':
(1234, 1)
(1234, 1)
(1234, 1)
(1234, 1)
In [3]: 
```
> PR: Warn when comm call creates text output

- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/nsview.py
- spyder_kernels/utils/tests/test_nsview.py
- That will be handled by Spyder instead.
- This also adds Numpy types to the namespace view, which are necessary for that purpose.
> PR: Remove handling of colors for object types

- setup.py
- Unfortunately `decorator` 5.0 breaks the Cython magic.
- This is tested on the Spyder side, not here.
> PR: Add a new dependency on decorator to fix the Cython magic

- spyder_kernels/utils/tests/test_iofuncs.py
- spyder_kernels/utils/tests/test_nsview.py
While running the test suite under numpy 1.20, the following warning appears:
```
/build/python-spyder-kernels/src/spyder-kernels-1.10.2/spyder_kernels/utils/tests/test_iofuncs.py:90: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
D = {'a': True, 'b': np.eye(4, dtype=np.complex)}
/build/python-spyder-kernels/src/spyder-kernels-1.10.2/spyder_kernels/utils/tests/test_nsview.py:69: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. …
```
> PR: Fix numpy.complex deprecation warning in tests

- spyder_kernels/console/kernel.py
This was failing probably since the release of Traitlets 5.
> PR: Fix setting tight layout in inline figures

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
Conda is incorrectly installing click 8 and that's breaking our tests.
> PR: Install click 7 to run our tests in Python 2

- spyder_kernels/console/kernel.py
This addresses https://github.com/spyder-ide/spyder/issues/15498
> PR: Redefine comm_manager method to avoid showing warning

- spyder_kernels/customize/utils.py
Addresses https://github.com/spyder-ide/spyder/issues/15417
> PR: Use backslash instead of slash for UMR path regex detection

- spyder_kernels/customize/spyderpdb.py
With this we can maintain the previous behavior (of not showing a message for skipped frames) by using a new attribute added to IPdb in IPython 7.24.1
> PR: Don't report skipped frames for IPython 7.24+ (Debugger)

- spyder_kernels/console/start.py
This avoids deleting the sys module if users want to import it in Spyder.
> PR: Clear argv before adding the exec lines that come from Spyder

- spyder_kernels/customize/spyderpdb.py
Get breakpoints every time `%debug` is called..
This is needed for https://github.com/spyder-ide/spyder/issues/15780
> PR: Fix %debug magic

- spyder_kernels/console/kernel.py
- That check was necessary for the old (i.e. Spyder 3) architecture but not for the new one.
- This was preventing to update correctly the Pdb state when going up/down in the stack frame.
> PR: Remove an unnecessary check when getting values in Pdb

- setup.py
- spyder_kernels/console/outstream.py
- spyder_kernels/console/start.py
This PR is work to enable colored output (by default) in the Spyder console. See https://github.com/spyder-ide/spyder/issues/1917, https://github.com/willmcgugan/rich/pull/1221, https://github.com/ipython/ipykernel/pull/683
Fixes #302
It adds `traitlets` as a new requirement, but since `ipykernel` already has this as a requirement this should have little impact.
@ccordoba12
> PR: Use an outstream with isatty() equal to True

- setup.py
- This is until we find the time to figure out how to support it.
- Also add Python 3.9 classifier.
> PR: Restrict jupyter-client to be less than version 7

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- requirements/python-27.txt
- setup.py
- spyder_kernels/py3compat.py
- spyder_kernels/utils/misc.py
- This avoids having to call repeatedly that function when computing lazy modules attributes.
- Addresses spyder-ide/spyder#16247
> PR: Memoize results of is_module_installed

- spyder_kernels/console/start.py
- spyder_kernels/customize/spydercustomize.py
- Other packages (e.g. the Pydev debugger) can also add a `runfile` function to `builtins`, which prevents using our own.
- This started to be a problem since IPykernel 6.3.0.
> PR: Avoid runfile to be shadowed by other packages

- requirements/tests.txt
- This helps to fix our tests because the current IPykernel package in Anaconda doesn't have a declared dependency in `ipython_genutils`.
- We don't need to declare that dependency here because it was fixed in IPykernel **6.3.1**.
> PR: Add `ipython_genutils` dependency for testing

- setup.py
- spyder_kernels/console/tests/test_console_kernel.py
According to the [migration guide](https://jupyter-client.readthedocs.io/en/master/migration.html), removing the `block` parameter should be all that is needed here. Let's see...
> PR: Remove upper constraint on jupyter_client

- spyder_kernels/console/start.py
For that we have Wurlitzer.
Fixes #316.
> PR: Disable the new mechanism to forward low-level output in IPykernel 6

- spyder_kernels/comms/frontendcomm.py
Those warnings only pollute the console.
Fixes #343.
> PR: Don't print DeprecationWarning's that come from comm handlers

- requirements/posix.txt
- requirements/windows.txt
- setup.py
We require now `ipython >=7.6.0,<8`
> PR: Constraint IPython version to avoid issues when its next major version is released

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
@ccordoba12 
Sorry for changing my mind. This is a less hacky version of https://github.com/spyder-ide/spyder-kernels/pull/351. I am more confident that this won't create subtle bugs. The only problem with this approach I could think of is that closures defined in the pdb prompt are early binding. This removes the difference between `globals()` and `frame.f_globals` that might have been problematic.
> PR: Implement a less hacky solution to fix namespace issues

- setup.py
This is necessary to work with its new async codebase in Spyder, which is completely different from the one in previous versions.
> PR: Increase minimal required version of jupyter_client to 7.0+ for Python 3

- setup.py
- In particular, this should fix `ZMQError: Address already in use` when restarting the kernel.
- Addresses spyder-ide/spyder#14739.
> PR: Require jupyter-client 7.1.0 to fix issues on Windows

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
- requirements/posix.txt
- requirements/python-27.txt
- requirements/windows.txt
- setup.py
- This fixes a bug with the Tk backend.
- Explicitly declare all our deps in the requirements files used for testing.
- Switch to conda-forge for testing because it's much more up to date.
> PR: Increase minimal required version of ipykernel to 6.6.1

- requirements/posix.txt
- requirements/windows.txt
- setup.py
This avoids a crash at startup in Spyder when using older versions.
> PR: Increase minimal required version of pyzmq for Python 3

- requirements/python-27.txt
- spyder_kernels/comms/commbase.py
- This error is shown in the console sometimes but it doesn't add any important information to users.
- See spyder-ide/spyder#17042 for the details.
> PR: Catch KeyError when closing comm

- spyder_kernels/utils/dochelpers.py
> PR: Catch error when validating if an object is defined in the namespace

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/kernel.py
Before we were showing this very long message, which is not very telling
Now we show this
Fixes #347.
> PR: Improve error message when setting a Matplotlib backend whose module is not present

- requirements/posix.txt
- requirements/tests.txt
- requirements/windows.txt
- setup.py
- That version addresses CVE-2022-21699
- This automatically drops support for Python 3.6
Fixes #344
> PR: Increase minimal required IPython version to 7.31.1

- requirements/posix.txt
- requirements/windows.txt
- setup.py
This helps to fix an error when restarting the kernel after setting an interactive Matplotlib backend.
> PR: Increase minimal required version of ipykernel to 6.9.2

- .github/workflows/linux-tests.yml
- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/mpl.py
This is necessary to correctly inform users in Spyder that a kernel restart is necessary when they set first the Qt5 backend, then Inline, then Tk.
To account for that possibility, we need a way to detect the current interactive backend (e.g. Qt5 or Tk) independently of the current one. Before we were assuming that if the current backend is Inline (as in the second step above), then you can switch to any interactive one, but that's actually not correct because it's not possible to have two interactive backends running at the same time.
> PR: Add new handler to detect the current Matplotlib interactive backend

- requirements/posix.txt
- requirements/windows.txt
- setup.py
That version solves several errors when Spyder is closed.
Addresses https://github.com/spyder-ide/spyder/issues/17776.
> PR: Increase minimal required version of jupyter_client to 7.3.1

- spyder_kernels/console/tests/test_console_kernel.py
test_get_interactive_backend is flaky. This adds a small waiting time to get rid of the flakyness.
> PR: Fix flaky test

- spyder_kernels/utils/dochelpers.py
- spyder_kernels/utils/tests/test_dochelpers.py
This was failing because we were using old Python 2 attributes for callables.
> PR: Fix getting args from functions or methods

- spyder_kernels/console/kernel.py
- spyder_kernels/customize/spyderpdb.py
See commit message for a detailed description. We have been using this patch for quite some time and haven’t experienced issues so far.
At least in theory, this should improve the performance of the debugger in Spyder (in terms of steps/second). In practical terms, performance gains are only noticeable with _very_ many variables in current scope. Think of about 80–100 variables on a rather old/slow machine, and > 200–300 variables on a rather fast one. Gains may be bigger with remote kernels, but I haven’t tested that
PS: Please let me know if I should provide instructions how to (roughly) measure the performance.
> PR: Eliminate unnecessary updates of the Variable Explorer while debugging

- spyder_kernels/console/kernel.py
- spyder_kernels/customize/spydercustomize.py
Update `os.environ['PYTHONPATH']` along with `sys.path`.
`PYTHONPATH` paths are inserted at position 0 instead of position 1 on `sys.path` update because the `<env>/bin` path is not included (why?), consistent with expected IPython behavior.
See spyder-ide/spyder#17512
> PR: Append paths that come from Spyder's Python path manager to the end of `sys.path`

- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
- spyder_kernels/customize/utils.py
On linux when processing window paths:
```
IPdb [5]: os.path.abspath("C:/Users")
Out  [5]: '/home/debian/spyder-kernels/C:/Users'
```
This PR changes the filename handling to fix https://github.com/spyder-ide/spyder/issues/18330
> PR: Fix debug filename path for remote debugging

- spyder_kernels/console/tests/test_console_kernel.py
In the test_console_kernel.py file, the tests use `client.execute`. using `client.execute_interactive` instead prints the errors and makes debugging easier.
> PR: Use `execute_interactive` to print errors during tests

- spyder_kernels/console/tests/test_console_kernel.py
Sometimes, the connection file is not yet written when the client tries to load it. This remove test flakyness.
> PR: Wait for connection file to be written

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/namespace_manager.py
- spyder_kernels/customize/spydercustomize.py
- spyder_kernels/customize/spyderpdb.py
This PR adds two functions to the comms:
- `request_pdb_stop` that enters the debugger immediately (at the next python interaction). If the kernel is not debugging, it creates a debugger.
- `raise_interrupt_signal` that raises an interrupt signal on request. This allows interrupting remote kernels.
The `shell.pdb_session` handling is improved as before it would not be unregistered in some cases. Now it returns the tracing pdb session. It handles recursive debugger by keeping a stack of debuggers.
A new function handles interrupt signals: `shell.spyderkernel_sigint_handler`. It is reset at every prompt to keep the behaviour constant from ipykernel which resets the SIGINT handler at every message (in `post_handler_hook`). It will play nice with a currently debugging shell. This completely …
> PR: Add handlers to interrupt executions and enter the debugger after that

- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
- Fixes #405.
- Addresses https://github.com/spyder-ide/spyder/issues/18856
Also remove unnecessary del (function returns which leads to the ref being deleted anyway)
> PR: Use debugging namespace when curframe is active

- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
Addresses spyder-ide/spyder#18434
> PR: Use `get_size` to get variable length for `get_var_properties` to prevent triggering Dask tasks

- spyder_kernels/console/shell.py
Expose spyder kernels version for checking from the frontend
> PR: Expose package version in SpyderShell

- spyder_kernels/comms/frontendcomm.py
Avoid accessing `sys.stdout` and `sys.stderr` multiple times in case another threads modifies it.
Might help with https://github.com/spyder-ide/spyder/issues/19735
> PR: Only access sys.stdout and sys.stderr once

- spyder_kernels/utils/iofuncs.py
From the original pull request (i.e. PR #424):
Hi, we are security researchers from the Advanced Research Center at [Trellix](https://www.trellix.com). We have began a campaign to patch a widespread bug named CVE-2007-4559. CVE-2007-4559 is a 15 year old bug in the Python tarfile package. By using extract() or extractall() on a tarfile object without sanitizing input, a maliciously crafted .tar file could perform a directory path traversal attack. We found at least one unsantized extractall() in your codebase and are providing a patch for you via pull request. The patch essentially checks to see if all tarfile members will be extracted safely and throws an exception otherwise. We encourage you to use this patch or your own solution to secure against CVE-2007-4559. Further technical …
> PR: Patch for CVE-2007-4559 Tar directory traversal

- spyder_kernels/utils/dochelpers.py
I have based this patch on the 2.x branch rather than the master branch; the patch would need the obvious modification to apply there (dedenting and changing the surrounding context).
Fixes #307
> PR: Replace deprecated `inspect.formatargspec` call

- spyder_kernels/comms/commbase.py
- spyder_kernels/utils/dochelpers.py
- spyder_kernels/utils/iofuncs.py
- spyder_kernels/utils/nsview.py
It seems like PY2 is still in 2.x, but not master, so I guess that master is the correct branch to target for this?
Just a minor cleanup.
> PR: Remove imports from __future__

- spyder_kernels/customize/tests/test_utils.py
The 'user site-packages in pathlist' test is the only one that fails on FreeBSD because the OS is not recognized. FreeBSD uses the same .local path as Darwin, so you can simply extend the if statement.
> PR: Add FreeBSD to `test_user_sitepackages_in_pathlist`

- spyder_kernels/console/shell.py
See ipython/ipykernel#1101 for context.
> PR: Make call to interrupt children processes work for IPykernel greater than 6.21.2

- requirements/python-27.txt
- setup.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
That's because distutils is going to be removed in Python 3.12
Fixes #440
> PR: Remove usage of `distutils.LooseVersion`

- spyder_kernels/console/tests/test_console_kernel.py
This also fixes our tests in `master`.
> PR: Remove unnecessary code for old IPykernel versions in our tests

- spyder_kernels/customize/spyderpdb.py
This is necessary to solve spyder-ide/spyder#20639 and partly for spyder-ide/spyder#20571 too.
> PR: Disable IPython's debugger skip functionality by default

- requirements/posix.txt
- requirements/windows.txt
- setup.py
This is necessary to address spyder-ide/spyder#21017.
> PR: Increase minimal required version of IPykernel to 6.23.2

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/utils/nsview.py
Part of https://github.com/spyder-ide/spyder/pull/20868
> PR: Add a global filter flag to settings

- spyder_kernels/utils/tests/test_iofuncs.py
The test `test_save_load_hdf5_files` saves its test file `test.h5` in the current directory, which is not helpful.  (If you run the tests prior to installing the package, the h5 file may end up in the resulting package, for example.)
This patch saves the `test.h5` in a temporary directory instead.
> Save temporary file in test to temporary location

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/console/start.py
- This was broken in the 2.4 series.
- Addresses spyder-ide/spyder#21310.
> PR: Restore compatibility with Python 2

- spyder_kernels/utils/dochelpers.py
- spyder_kernels/utils/tests/test_dochelpers.py
- Discard IPython default signatures in case we're able to find others.
- Get signatures written in multiple lines at the beginning of docstrings.
> PR: Improve getting signatures from text

- setup.py
- That's because that version broke the `%autoreload` magic.
- This is required to address spyder-ide/spyder#21472.
> PR: Skip IPython 8.17.1 in our dependencies for Python 3.9+

- spyder_kernels/comms/frontendcomm.py
- spyder_kernels/comms/utils.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/code_runner.py
- spyder_kernels/customize/spyderpdb.py
- spyder_kernels/customize/tests/test_umr.py
- spyder_kernels/customize/umr.py
- spyder_kernels/utils/mpl.py
Goes with https://github.com/spyder-ide/spyder/pull/21320
> PR: Simplify kernel configuration

- spyder_kernels/console/kernel.py
Handle the new options for the font size and the bottom edge for inline plots, which are added in PR spyder-ide/spyder#21566.
> PR: Handle new Inline backend options `fontsize` and `bottom`

- spyder_kernels/console/kernel.py
Also, avoid any error when trying to remove them and cancel some linting warnings.
> PR: Save faulthandler files under `xdg_data_home/spyder` on Linux

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- requirements/posix.txt
- requirements/windows.txt
- setup.py
- Addresses spyder-ide/spyder#21299.
- This requires updating our dependency on IPykernel to `>=6.29.3,<7`.
> PR: Fix hangs with Maplotlib interactive backends

- spyder_kernels/customize/code_runner.py
- spyder_kernels/customize/spyderpdb.py
- spyder_kernels/customize/utils.py
Spyder PR: https://github.com/spyder-ide/spyder/pull/21875
> PR: Allow magic to edit locals while debugging

- spyder_kernels/comms/utils.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- That probably broke in one of the latest IPykernel updates.
- Prevent unnecessary messages when setting the Matplotlib backend and calling the `%pylab` magic. Those messages were shown when changing options related to that in Spyder.
- Fix reporting to Spyder that the Inline backend was set for IPython 8.24+.
> PR: Fix Matplotlib interactive backend detection

- spyder_kernels/console/tests/test_console_kernel.py
- The latest changes to detect interactive backends fix it.
- Only skip it for the Qt backend on CIs because it fails there (although it passes locally).
Fixes #457.
> PR: Run `test_get_interactive_backend` again on Mac

- spyder_kernels/console/kernel.py
- spyder_kernels/utils/mpl.py
Matplotlib get_backend returns lowercase in version >=3.9.0.
Update MPL_BACKENDS_TO_SPYDER to accommodate.
> PR: Fix detecting Matplotlib backend for its 3.9.0 version

- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/console/start.py
This fixes an issue where:
* Spyder's inline graphics preferences were not applied when toggling from inline to interactive and back to inline.
* Matplotlib's `rcParams` are over-written by Spyder's inline preferences even with the preference set for an interactive backend.
For more detail, see spyder-ide/spyder#22034.
> PR: Fix issue where Spyder's inline graphics preferences were not applied

- requirements/posix.txt
- requirements/windows.txt
- spyder_kernels/console/outstream.py
Addresses spyder-ide/spyder#22181.
> PR: Add filtering logic for stream data and constraint `setuptools` version

- spyder_kernels/customize/spydercustomize.py
This is necessary for spyder-ide/spyder#22382.
> PR: Remove `TMPDIR` env var in case it was set by Spyder

- spyder_kernels/customize/spydercustomize.py
- This is necessary for https://github.com/spyder-ide/spyder/pull/22394.
- And it fixes a regression introduced by #498.
> PR: Restore `TMPDIR` env var if it was available on the Spyder side

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
This is necessary so we can run our tests for backported PRs.
> PR: Update workflows to run in the `3.x` branch (CI)

- README.md
CZI is our main sponsor right now.
> PR: Replace Quansight logo by CZI one in Readme

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
- .github/workflows/macos-tests.yml
- .github/workflows/windows-tests.yml
* Update to `setup-miniconda@v3` and `codecov-action@v4`.
Resolves "The following actions use a deprecated Node.js version and will be forced to run on node20: conda-incubator/setup-miniconda@v2, codecov/codecov-action@v3"
> PR: Update workflow actions (CI)

- spyder_kernels/customize/code_runner.py
- spyder_kernels/customize/utils.py
Addresses spyder-ide/spyder#22574
> Make `glob` and `loc` kwargs of `debug_exec`

- spyder_kernels/console/shell.py
- This can be necessary when there's a mismatch between the installed versions of IPython, matplotlib and matplotlib-inline.
- Addresses spyder-ide/spyder#22420
> PR: Manually register the Matplotlib inline backend in case it wasn't

- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/console/start.py
- spyder_kernels/customize/code_runner.py
- spyder_kernels/customize/umr.py
- spyder_kernels/utils/style.py
Part of spyder-ide/spyder#22412
> PR: Add logic to handle traceback color configuration

- RELEASE.md
Some instructions were not necessary anymore and others needed to be updated.
> PR: Improve release instructions for the new backporting workflow

- .github/workflows/linux-pip-tests.yml
- .github/workflows/linux-tests.yml
That version has the right system packages we need to run our tests.
> PR: Use an older Ubuntu version on CIs

- spyder_kernels/console/kernel.py
- spyder_kernels/console/start.py
- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spydercustomize.py
* Input to `update_syspath` is now the new paths as list of strings (instead of dictionary) and whether to append/prepend the new paths to `sys.path`. Old paths are not needed. The original `sys.path` is stored at module import and used to construct new `sys.path` with new paths sent from Spyder, rather than removing old paths.
* Remove obsolete `set_spyder_pythonpath`. Spyder now sends new paths after kernel startup.
> PR: Add feature to prepend/append PYTHONPATH to sys.path

- spyder_kernels/console/tests/test_console_kernel.py
This is to know if only one or both are failing.
This also properly mark a test as skipped on Windows.
I guess we could make it a parametrize call, but
this would make it complicated to parametrize.
> PR: Split `test_interrupt` into two tests

- spyder_kernels/console/tests/test_console_kernel.py
- spyder_kernels/customize/spyderpdb.py
- spyder_kernels/utils/tests/test_iofuncs.py
A number of methods of ipykernel can optinally return `awaitable[T]` instead of just `T`, this is the case for `do_complete`.
I think it's a mistake ; see ipython/ipykernel#1295 ; in particular because it's easy to forget / hard to properly type-check, and I'd like to make it mandatory in the long term to have await.
Spyder seem to not handle the case where do_completer return an awaitable (or more partiularly is `do_complete` is a coroutine function.
This tries to handle it – and as of course `do_completer` _can_ be async, all caller _must_ be async. So I try to do all the required updates.
Note: I also add explict imports in some test, to get better error message in case those deps are not installed.
> Handle async do_complete in the debugger

- conftest.py
- requirements/tests.txt
- setup.py
- spyder_kernels/console/kernel.py
- spyder_kernels/console/tests/test_console_kernel.py
Some versions of pytest do auto run async tests,
recents one do not, and marking with
`@pytest.mark.anyio` also test with multiple
runner if installed.
Handle case where do_complete is both async and
sync, and make _do_complete always async.
I only found mentions of the private _do_complete
in spyder kernel, so if present somewhere else you
might need to lift the if awaitable one level up.
> PR: Fix some async do completes

- spyder_kernels/utils/nsview.py
- spyder_kernels/utils/tests/test_nsview.py
When displaying a NumPy array of strings, use `str` to convert the array to a string instead of using the default description "ndarray object of numpy module".
@ccordoba12 You turned off displaying the contents of string arrays in PR spyder-ide/spyder#5028 where you specified that only the contents of numeric arrays should be displayed. I presume that you did so to prevent problems with displaying arbitrary arrays, but I think string arrays are safe.
This fixes issue spyder-ide/spyder#22570.
> PR: Display contents of string arrays

- spyder_kernels/utils/nsview.py
- spyder_kernels/utils/tests/test_nsview.py
Support getting the value of a variable of type `frozenset`. The value will be shown as "frozenset({...})", similar as when you print the variable. Also add a small test for this.
> PR: Support `frozenset` in namespace view

- spyder_kernels/utils/nsview.py
- spyder_kernels/utils/tests/test_nsview.py
Support variables of type `pathlib.Path` and variables containing `None` in `value_to_display()`, so that they can be displayed in Spyder's Variable Explorer. Also add tests for this.
Variables of type `pathlib.Path` are converted using `str()`. The alternative would be to use `repr()`, which results in the variable `path` in the example below to be displayed as `PosixPath('/home/jitse/spyder-kernels')`. As explained in https://github.com/spyder-ide/spyder/issues/22351#issue-2467604479:
> The repr has the advantage as it gives a clear indicator in how to instantiate a new Path.
>
>  However displaying the printed version of the str form, where the escape characters are processed has the advantage in that it matches what is typically displayed in the Operating System and is consistent to …
> PR: Support pathlib and None in namespace view

- requirements/posix.txt
- requirements/windows.txt
- setup.py
- Versions between 5.12 and 5.14.2 have a nasty bug that prevents setting the Matplotlib inline backend formats.
- This is necessary to address spyder-ide/spyder#24390
> PR: Add minimal required version of `traitlets`

- pyproject.toml
- requirements/posix.txt
- requirements/windows.txt
- spyder_kernels/console/kernel.py
- spyder_kernels/console/shell.py
- spyder_kernels/console/start.py
- spyder_kernels/utils/misc.py
Fixes #543
Part of https://github.com/spyder-ide/spyder/issues/23911
Related with https://github.com/spyder-ide/spyder/pull/24806
TODO:
> PR: Add support for IPython 9

- pyproject.toml
- Needed for spyder-ide/spyder#25034.
> PR: Bump minimal supported IPython version to 8.15
